Major Repository Rennovation, Branch: develop
expanded-mod-team/RL-Expanded-Rewrite pull request #76
Opened 2020-11-17 00:18 UTC by TrainDoctor

This revamps the develop branch and integrates a bunch of changes I am proposing to bring to this repo.

Preview the changes [here](https://github.com/TrainDoctor/RL-Expanded-Rewrite)

2020-11-21 01:41 UTC, pervyrogue commented on game/_script_/actors/Actor.rpy
This needs moved out of renpy files and into an issue.

Documentation of files should follow docblock formatting.

2020-11-21 01:43 UTC, pervyrogue reviewed
Move of major mechanics to separate files is great.

2020-11-21 01:44 UTC, pervyrogue requested changes
Why did we remove this?

Oni specific items can be removed when repo is forked and sanitized for use in other projects.

2020-11-21 01:46 UTC, pervyrogue reviewed
Image Test worked. More documentation of test setup would have been preferred.

Note to self: Comment more inside renpy specific scripting.

2020-11-21 01:48 UTC, pervyrogue commented on game/Locations.rpy
> +define testenv = Location("University Square", adjacent=
Why did we remove university_square? testenv should have been a separate define.

2020-11-21 01:51 UTC, pervyrogue commented on game/Events.rpy
> +    $ renpy.show("study_day")
Avoid equivalent statements in renpy scripts unless using functions/variables/etc.

2020-11-21 01:53 UTC, pervyrogue commented on game/screens.rpy
> +        textbutton _("Test Enviroment") action Start("testenv")
Good use of the main menu. Add a conditional for display reliant on config.developer

2020-11-21 01:56 UTC, pervyrogue commented on game/Locations.rpy
> +        "Shop": # TrainDoc: wtf are we going to do w/ the shop? it's so half baked lol
Create related issue and use REF or SEE codetag with issue number.

2020-11-21 01:57 UTC, pervyrogue commented on game/Events.rpy
> +    # TrainDoc:
Use author docblock param instead of name tags in comments.

2020-11-21 02:01 UTC, pervyrogue requested changes
Discuss and change file structure to meet #80.

2020-11-24 01:06 UTC, TrainDoctor commented
> Why did we remove this?
> 
> Oni specific items can be removed when repo is forked and sanitized for use in other projects.

This doesn't have any code attached to it so I'm not sure what needs to be changed.

2020-11-24 01:10 UTC, TrainDoctor commented
I've resolved to remove all the non-github issue related changes and from my fork and to attempt another pull request.

2020-11-24 01:10 UTC, closed without merging