Actor refactoring and new classes
expanded-mod-team/RL-Expanded-Rewrite pull request #89
Opened 2020-11-27 17:22 UTC by Mederic64

https://github.com/expanded-mod-team/RL-Expanded-Rewrite/issues/3

2020-11-27 17:46 UTC, TrainDoctor commented
I'm liking the look of this already but this will definitely need some review. The location of class declarations being moved may cause some problems. This is due to how kwargs are processed in your base Actor doesn't respect a unwritten intent to process custom kwargs before kwargs that the base ``Character()`` function take, sorry about that.

2020-11-30 23:25 UTC, TrainDoctor reviewed
Looks really good. Going to defer to @pervyrogue for final review.

2020-11-30 23:25 UTC, TrainDoctor commented on game/_base/Actor.rpy
> +            self.money = 0
```suggestion
```
We are still unsure of how the inventory of an Actor will function and whether the inventory will contain information related money, xp etc.

2020-11-30 23:25 UTC, TrainDoctor commented on game/_base/ActorInteractable.rpy
> +                self[stat.key] = stat.value
I will need @pervyrogue to go over this and determine whether or not this is the way we want to handle statistics as such.

2020-11-30 23:27 UTC, pervyrogue commented on game/_base/ActorInteractable.rpy
> +    class InteractableActorStatistic(renpy.store.object):
Class should be defined before InteractableActor, then an instance created and stored inside InteractableActor. This is Composition and creates a definitive and proper association between these objects.

2020-11-30 23:27 UTC, pervyrogue commented on game/_base/ActorInteractable.rpy
> +    class Wardrobe(renpy.store.object):
Class should be defined before InteractableActor, then an instance created and stored inside InteractableActor. This is Composition and creates a definitive and proper association between these objects.

2020-11-30 23:28 UTC, pervyrogue commented on game/_base/ActorInteractable.rpy
> +    class Outfit(renpy.store.object):
Class should be defined before Wardrobe, then an instance created and stored inside InteractableActor. As an Outfit is something that can exist on its own, this is called Aggregation.

2020-12-01 02:37 UTC, pervyrogue commented on game/_base/Actor.rpy
> +            TODO: Write an intent for what the BASIC-ACTOR does above *
What exactly **_does_** this do?

2020-12-01 02:38 UTC, pervyrogue commented on game/_base/Actor.rpy
> +    class Inventory(renpy.store.object):
Determine if inventory needs to be an object. If it does, add special functions so object reacts like a list.

2020-12-01 02:38 UTC, pervyrogue commented on game/_base/ActorInteractable.rpy
> +            Wardrobe contains the Outfits for a character
Good docblock!

2020-12-01 03:12 UTC, TrainDoctor commented on game/_base/Actor.rpy
> +            TODO: Write an intent for what the BASIC-ACTOR does above *
This is leftover from an old implementation that is could now be replaced by Actor rather than ActorInteractable. Of course I would need to change normal actors but we'll address that later.

2020-12-01 19:00 UTC, TrainDoctor requested changes
Once composition formatting is met, I can resolve the majority.

2020-12-02 03:06 UTC, TrainDoctor commented on game/_base/Actor.rpy
>                  if config.developer print("color was not found")
```suggestion
                if config.developer: print("color was not found")
```

2020-12-02 05:16 UTC, TrainDoctor reviewed
Here's a few more.

2020-12-02 11:45 UTC, Mederic64 commented on game/_base/ActorInteractable.rpy
> +            self.coiffure.active = kwargs.get('coiffures', {'default', 'default'})
noooo my coiffures :(

2020-12-02 20:01 UTC, TrainDoctor commented on game/_base/Actor.rpy
> +            TODO: Write an intent for what the BASIC-ACTOR does above *
Addressed in #90

2020-12-02 20:17 UTC, pervyrogue commented on game/_base/ActorInteractable.rpy
> +                self[stat.key] = stat.value
This is a valid way to handle this. And since we don't always know what stats we need, this should work.

2020-12-22 21:25 UTC, merged

2020-12-22 21:26 UTC, pervyrogue commented
Reviewed and merged PR. Some parts may be removed later but, do not negatively affect the project at this point.